# Nexus ~ Config
#
# > In case you need any further information on certain
# > configuration options, feel free to have a loot at:
# > https://github.com/mn7cc/nexus/wiki/config.yml

config:
    mysql:
        enable: false
        hostname: localhost
        port: 3306
        username: root
        password: password
        database: minecraft